#!/usr/bin/env python3
"""
generate_metrics_report.py

Generate a structured metrics definition report for a given project or feature.

Usage:
    python generate_metrics_report.py --project "My App" --goal "Grow user base" --output report.md
"""
import argparse
import datetime
from pathlib import Path


REPORT_TEMPLATE = """\
# Metrics Plan: {project}

**Date**: {date}
**Goal**: {goal}

---

## Primary KPIs

| Metric | Definition | Target | Owner |
|--------|------------|--------|-------|
| Monthly Active Users | Unique users with at least 1 session in 30 days | +10% MoM | Product |
| Activation Rate | % of new signups who complete onboarding | > 60% | Product |
| 7-Day Retention | % of new users active 7 days after signup | > 40% | Product |

## Supporting Metrics

| Metric | Definition |
|--------|------------|
| New Signups | New user registrations per week |
| DAU/MAU Ratio | Daily active ÷ monthly active (engagement depth) |
| Feature Adoption | % of users who used each core feature |
| Error Rate | % of API requests returning 5xx errors |

## Event Tracking Plan

| Event Name | Trigger | Key Properties |
|-----------|---------|----------------|
| `user_signed_up` | New registration completes | `source`, `plan` |
| `onboarding_completed` | User completes onboarding flow | `steps_completed`, `time_taken_seconds` |
| `feature_used` | User interacts with core feature | `feature_name`, `session_id` |
| `session_started` | App session begins | `platform`, `source` |

## Reporting Views

1. **DAU/MAU trend** — Time series, daily, last 90 days
2. **Activation funnel** — Step-by-step funnel from signup → first value
3. **Retention cohort table** — By signup week, 7/14/30 day retention
4. **Feature adoption bar chart** — % adoption per feature

## Measurement Notes

- Use ISO 8601 timestamps (UTC) for all events
- Deduplicate sessions by user_id + calendar day for MAU
- Exclude internal/test users from all metrics
- Review KPIs weekly; full review monthly

---
*Generated by generate_metrics_report.py on {date}*
"""


def generate_report(project: str, goal: str, output: str) -> None:
    date = datetime.date.today().isoformat()
    content = REPORT_TEMPLATE.format(project=project, goal=goal, date=date)

    out_path = Path(output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"Metrics report written to: {out_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a metrics definition report")
    parser.add_argument("--project", required=True, help="Project or feature name")
    parser.add_argument("--goal", required=True, help="Primary business goal")
    parser.add_argument("--output", default="metrics-report.md", help="Output file path")
    args = parser.parse_args()
    generate_report(args.project, args.goal, args.output)


if __name__ == "__main__":
    main()
